env:
  global:
    - CC_TEST_REPORTER_ID=ABC123
language: ruby
cache:
  - bundler
before_install:
  - nvm install --lts
  - gem install rspec
  - gem install coveralls
  - gem install colorize
  - gem install w3c_validators
before_script:
  - bundle install --no-deployment --jobs=3 --retry=3
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls