language: ruby
cache:
  - bundler
before_install:
  - nvm install --lts
  - gem install rspec
before_script:
  - bundle install --no-deployment --jobs=3 --retry=3
script:
  - rspec
after_success:
  - coveralls